# Generated by Django 2.0.7 on 2018-07-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_activity_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questino_text',
            new_name='question_text',
        ),
    ]
