# Generated by Django 2.0.7 on 2018-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20180722_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
