# Generated by Django 2.0.7 on 2018-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
